spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/go2climb?useSSL=false
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  springdoc:
    api-docs:
      groups:
        enabled: true
      path: "/api-docs"
    swagger-ui:
      path: "/swagger-ui/index.html"
      oauth:
        client-id: spring_client_api_rest
        client-secret: UeXyH4K1p6XxB6rDHwwROdqzc7cw9uaS

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-go2climb-dev
          jwk-set-uri: http://localhost:8080/realms/spring-go2climb-dev/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring_client_api_rest
