spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54173/go2climb?useSSL=false
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  springdoc:
    api-docs:
      groups:
        enabled: true
      path: "/api-docs"
    swagger-ui:
      path: "/swagger-ui.html"

server:
  port: 8080
